import { useAvailableOptions } from './useAvailableOptions.svelte';

const currencyMetadata: Record<string, { name: string; icon: string }> = {
  USD: { name: 'US Dollar', icon: '🇺🇸' },
  EUR: { name: 'Euro', icon: '🇪🇺' },
  BRL: { name: 'Brazilian Real', icon: '🇧🇷' },
  ARS: { name: 'Argentine Peso', icon: '🇦🇷' },
  GBP: { name: 'British Pound', icon: '🇬🇧' },
  PLN: { name: 'Polish Złoty', icon: '🇵🇱' },
  JPY: { name: 'Japanese Yen', icon: '🇯🇵' },
  CAD: { name: 'Canadian Dollar', icon: '🇨🇦' },
  AUD: { name: 'Australian Dollar', icon: '🇦🇺' },
  CHF: { name: 'Swiss Franc', icon: '🇨🇭' },
  CNY: { name: 'Chinese Yuan', icon: '🇨🇳' },
  INR: { name: 'Indian Rupee', icon: '🇮🇳' },
  MXN: { name: 'Mexican Peso', icon: '🇲🇽' },
  ZAR: { name: 'South African Rand', icon: '🇿🇦' },
  SEK: { name: 'Swedish Krona', icon: '🇸🇪' },
  NOK: { name: 'Norwegian Krone', icon: '🇳🇴' },
  DKK: { name: 'Danish Krone', icon: '🇩🇰' },
  NZD: { name: 'New Zealand Dollar', icon: '🇳🇿' },
  SGD: { name: 'Singapore Dollar', icon: '🇸🇬' },
  HKD: { name: 'Hong Kong Dollar', icon: '🇭🇰' },
  KRW: { name: 'South Korean Won', icon: '🇰🇷' },
  TRY: { name: 'Turkish Lira', icon: '🇹🇷' },
  RUB: { name: 'Russian Ruble', icon: '🇷🇺' },
  THB: { name: 'Thai Baht', icon: '🇹🇭' },
  MYR: { name: 'Malaysian Ringgit', icon: '🇲🇾' },
  PHP: { name: 'Philippine Peso', icon: '🇵🇭' },
  IDR: { name: 'Indonesian Rupiah', icon: '🇮🇩' },
  VND: { name: 'Vietnamese Dong', icon: '🇻🇳' },
  COP: { name: 'Colombian Peso', icon: '🇨🇴' },
  CLP: { name: 'Chilean Peso', icon: '🇨🇱' },
  PEN: { name: 'Peruvian Sol', icon: '🇵🇪' },
  UAH: { name: 'Ukrainian Hryvnia', icon: '🇺🇦' },
  AED: { name: 'UAE Dirham', icon: '🇦🇪' },
  SAR: { name: 'Saudi Riyal', icon: '🇸🇦' },
  QAR: { name: 'Qatari Riyal', icon: '🇶🇦' },
  KWD: { name: 'Kuwaiti Dinar', icon: '🇰🇼' },
  NGN: { name: 'Nigerian Naira', icon: '🇳🇬' },
  KES: { name: 'Kenyan Shilling', icon: '🇰🇪' },
  GHS: { name: 'Ghanaian Cedi', icon: '🇬🇭' },
  UGX: { name: 'Ugandan Shilling', icon: '🇺🇬' },
  VES: { name: 'Venezuelan Bolívar', icon: '🇻🇪' },
  UYU: { name: 'Uruguayan Peso', icon: '🇺🇾' },
  BOB: { name: 'Bolivian Boliviano', icon: '🇧🇴' },
  CRC: { name: 'Costa Rican Colón', icon: '🇨🇷' },
  GTQ: { name: 'Guatemalan Quetzal', icon: '🇬🇹' },
  HNL: { name: 'Honduran Lempira', icon: '🇭🇳' },
  NIO: { name: 'Nicaraguan Córdoba', icon: '🇳🇮' },
  PAB: { name: 'Panamanian Balboa', icon: '🇵🇦' },
  PYG: { name: 'Paraguayan Guarani', icon: '🇵🇾' },
  DOP: { name: 'Dominican Peso', icon: '🇩🇴' },
  JMD: { name: 'Jamaican Dollar', icon: '🇯🇲' },
  TTD: { name: 'Trinidad Dollar', icon: '🇹🇹' },
  BSD: { name: 'Bahamian Dollar', icon: '🇧🇸' },
  BBD: { name: 'Barbadian Dollar', icon: '🇧🇧' },
  BZD: { name: 'Belize Dollar', icon: '🇧🇿' },
  XOF: { name: 'West African CFA', icon: '🌍' },
  XAF: { name: 'Central African CFA', icon: '🌍' },
  MAD: { name: 'Moroccan Dirham', icon: '🇲🇦' },
  TND: { name: 'Tunisian Dinar', icon: '🇹🇳' },
  EGP: { name: 'Egyptian Pound', icon: '🇪🇬' },
  ILS: { name: 'Israeli Shekel', icon: '🇮🇱' },
  JOD: { name: 'Jordanian Dinar', icon: '🇯🇴' },
  LBP: { name: 'Lebanese Pound', icon: '🇱🇧' },
  PKR: { name: 'Pakistani Rupee', icon: '🇵🇰' },
  BDT: { name: 'Bangladeshi Taka', icon: '🇧🇩' },
  LKR: { name: 'Sri Lankan Rupee', icon: '🇱🇰' },
  NPR: { name: 'Nepalese Rupee', icon: '🇳🇵' },
  MMK: { name: 'Myanmar Kyat', icon: '🇲🇲' },
  KHR: { name: 'Cambodian Riel', icon: '🇰🇭' },
  LAK: { name: 'Lao Kip', icon: '🇱🇦' },
  BND: { name: 'Brunei Dollar', icon: '🇧🇳' },
  TWD: { name: 'Taiwan Dollar', icon: '🇹🇼' },
  HRK: { name: 'Croatian Kuna', icon: '🇭🇷' },
  BGN: { name: 'Bulgarian Lev', icon: '🇧🇬' },
  RON: { name: 'Romanian Leu', icon: '🇷🇴' },
  CZK: { name: 'Czech Koruna', icon: '🇨🇿' },
  HUF: { name: 'Hungarian Forint', icon: '🇭🇺' },
  ISK: { name: 'Icelandic Króna', icon: '🇮🇸' },
  BAM: { name: 'Bosnian Mark', icon: '🇧🇦' },
  MKD: { name: 'Macedonian Denar', icon: '🇲🇰' },
  ALL: { name: 'Albanian Lek', icon: '🇦🇱' },
  RSD: { name: 'Serbian Dinar', icon: '🇷🇸' },
  GEL: { name: 'Georgian Lari', icon: '🇬🇪' },
  AZN: { name: 'Azerbaijani Manat', icon: '🇦🇿' },
  AMD: { name: 'Armenian Dram', icon: '🇦🇲' },
  BYN: { name: 'Belarusian Ruble', icon: '🇧🇾' },
  MDL: { name: 'Moldovan Leu', icon: '🇲🇩' },
  KZT: { name: 'Kazakhstani Tenge', icon: '🇰🇿' },
  UZS: { name: 'Uzbekistani Som', icon: '🇺🇿' },
  TJS: { name: 'Tajikistani Somoni', icon: '🇹🇯' },
  KGS: { name: 'Kyrgyzstani Som', icon: '🇰🇬' },
  TMT: { name: 'Turkmenistani Manat', icon: '🇹🇲' }
};

export function useAvailableCurrencies() {
  const { options } = useAvailableOptions({
    tagName: 'f',
    transform: (v) => v.toUpperCase(),
    metadata: currencyMetadata,
    defaultIcon: '💱',
    allOption: { id: 'all', name: 'All', icon: '🌍' },
    sortBy: 'id'
  });

  return {
    get currencies() {
      return options;
    }
  };
}
